# Generated by Django 3.1.7 on 2021-03-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Cayegory',
        ),
    ]
