# Generated by Django 3.1.7 on 2021-03-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210325_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cayegory',
            new_name='Category',
        ),
    ]
